language: python
python: 2.7
sudo: false

env:
    - TOX_ENV=py27-twlatest
    - TOX_ENV=pypy-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=py33-twtrunk
    - TOX_ENV=py34-twtrunk
    - TOX_ENV=pyflakes
    - TOX_ENV=cov
    - TOX_ENV=docs

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
    email: false
