language: python
sudo: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35

    - python: 2.7
      env: TOXENV=pyflakes
    - python: 2.7
      env: TOXENV=cov
    - python: 2.7
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=apidocs
    - python: 2.7
      env: PUSH_DOCS=true

  fast_finish: true

env:
  global:
    - secure: "Zmj7rrKx4z3JyaKNJUzILhMSESf7tCPBt9ad67veaX+fwYlJzrHUq+iy+5RXSye/g3vpsfehpKs/F2bAQcmX1ysLDOvd8w+UvwQPRi/GXxvVn7CHD6C4rpiSJAJHbCk7FZwQlo8P6VE8qiqUMCJcXjnjl63egkvJlkl6+rbE00E="

install:
  - pip install tox

script:
  - if [[ -n "${TOXENV}" ]]; then tox; fi
  - if [[ "$PUSH_DOCS" == "true" ]]; then ./.travis/build_docs.sh; fi

notifications:
  email: false
